---
title: "Publications"
---

Kekecs, Z., Palfi, B., Szaszi, B., Szecsi, P., Zrubka, M., Kovacs, M., ... & Aczel, B. (2023). Raising the value of research studies in psychological science by increasing the credibility of research reports: the transparent Psi project. Royal Society Open Science, 10(2), 191375.

Kekecs, Z., Nyiri, B., Alldredge, C., Cserni, B., Rizzo, P., Domok, B., ... & Elkins, G. (2024). The effectiveness of hypnoanalgesia using conventional and placebo hypnosis induction. The Journal of Pain, 104519.

Koch, M., Szabó, É., Varga, C., Soós, V., Prenek, L., Porcsa, L., ... & Pozsgai, É. (2023). Retrospective study of cancer patients' predictive factors of care in a large, Hungarian tertiary care centre. BMJ open, 13(5), e070320.

Girán, J., Girán, K. A., Ormándlaky, D., Pozsgai, É., Kiss, I., & Kollányi, Z. (2023). Determinants of pupils' energy drink consumption--findings from a Hungarian primary school. Heliyon, 9(5).

Varga, C., Springó, Z., Koch, M., Prenek, L., Porcsa, L., Bellyei, S., ... & Pozsgai, É. (2024). Predictive factors of basic palliative and hospice care among patients with cancer visiting the emergency department in a Hungarian tertiary care center. Heliyon, 10(8).
